[project]
name = "agent-build-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "json5>=0.12.0",
    "qwen-agent[code-interpreter,gui,mcp,rag]>=0.0.22",
]
